In [19]:
# environment set up
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import pandas as pd
import time
import ast
from scipy import stats as st

# working folder
directory = os.environ['DATA_DIR']

In [20]:
spectrum_len = 500 # automate this
parent_dir = os.environ['PWD']
stddata_path = os.path.join(os.environ['DATA_DIR'], "StdData-" + str(spectrum_len))
os.chdir(os.path.join(parent_dir, "lab-notebook", "smunukutla"))

In [21]:
data = pd.read_csv("data.csv", sep=",")
record_nums = data.iloc[0, :].tolist()
spectrum_names = data.iloc[1, :].tolist()
y = data.iloc[2, :].astype(int).tolist()
y = np.reshape(y, (len(y), 1))
num_samples = len(y)

In [22]:
data

0           1           2           3           4           5  \
0       00108       00114       00120       00124       00130       00142   
1  Actinolite  Actinolite  Actinolite  Actinolite  Actinolite  Actinolite   
2           4           4           4           4           4           4   

            6           7           8           9  ...    156    157    158  \
0       00148       00154       00158       00177  ...  10896  10917  10938   
1  Actinolite  Actinolite  Actinolite  Actinolite  ...  Topaz  Topaz  Topaz   
2           4           4           4           4  ...      0      0      0   

     159    160    161    162    163    164    165  
0  10946  10967  10988  11009  11030  11051  11072  
1  Topaz  Topaz  Topaz  Topaz  Topaz  Topaz  Topaz  
2      0      0      0      0      0      0      0  

[3 rows x 166 columns]

In [23]:
spectra = np.zeros((num_samples,spectrum_len))

In [24]:
for i in range(len(record_nums)):
    data = pd.read_csv(os.path.join(stddata_path,"{}.csv".format(record_nums[i])))
#     if i == 0:
#         wavelengths[i,:] = data.iloc[:, 0].to_numpy()
    spectra[i,:] = data.iloc[:, 1].to_numpy()

In [26]:
data

wavelength  reflectance
0      0.370000     0.878464
1      0.374269     0.878143
2      0.378537     0.875394
3      0.382806     0.877019
4      0.387074     0.878757
5      0.391343     0.877592
6      0.395611     0.878095
7      0.399880     0.879440
8      0.404148     0.877743
9      0.408417     0.878107
10     0.412685     0.881499
11     0.416954     0.880381
12     0.421222     0.881388
13     0.425491     0.883255
14     0.429760     0.884304
15     0.434028     0.887466
16     0.438297     0.887674
17     0.442565     0.887932
18     0.446834     0.892096
19     0.451102     0.890961
20     0.455371     0.896223
21     0.459639     0.895942
22     0.463908     0.896039
23     0.468176     0.897699
24     0.472445     0.898780
25     0.476713     0.903992
26     0.480982     0.903621
27     0.485251     0.905302
28     0.489519     0.905606
29     0.493788     0.904993
..          ...          ...
470    2.376212     0.866352
471    2.380481     0.867309
472    2.384749     0.868267
473    2.389018     0.868973
474    2.393287     0.869576
475    2.397555     0.870178
476    2.401824     0.867921
477    2.406092     0.861829
478    2.410361     0.855737
479    2.414629     0.849645
480    2.418898     0.844369
481    2.423166     0.842158
482    2.427435     0.839947
483    2.431703     0.837735
484    2.435972     0.835524
485    2.440240     0.833122
486    2.444509     0.827519
487    2.448778     0.821917
488    2.453046     0.816314
489    2.457315     0.810712
490    2.461583     0.805109
491    2.465852     0.799507
492    2.470120     0.791996
493    2.474389     0.784417
494    2.478657     0.776838
495    2.482926     0.769259
496    2.487194     0.761680
497    2.491463     0.754101
498    2.495731     0.746523
499    2.500000     0.735945

[500 rows x 2 columns]

In [27]:
spectra.shape

(166, 500)

In [30]:
y_cat = to_categorical(y)

In [31]:
from sklearn.decomposition import DictionaryLearning

In [32]:
model = DictionaryLearning(n_components=10, alpha=1, verbose=True)

In [33]:
results = model.fit_transform(data)

[dict_learning] .++++++++.+++++.++.+.+.+.+.+.+.+.+......................................................................


In [37]:
for row in results:
    print(row)

[0.         0.         0.         0.         0.         0.
 0.         0.93341548 0.         0.        ]
[0.         0.         0.         0.         0.         0.
 0.         0.93557111 0.         0.        ]
[0.         0.         0.         0.         0.         0.
 0.         0.93572659 0.         0.        ]
[0.        0.        0.        0.        0.        0.        0.
 0.9394848 0.        0.       ]
[0.         0.         0.         0.         0.         0.
 0.         0.94333666 0.         0.        ]
[0.         0.         0.         0.         0.         0.
 0.         0.94479684 0.         0.        ]
[0.        0.        0.        0.        0.        0.        0.
 0.9476311 0.        0.       ]
[0.         0.         0.         0.         0.         0.
 0.         0.95115894 0.         0.        ]
[0.         0.         0.         0.         0.         0.
 0.         0.95218099 0.         0.        ]
[0.         0.         0.         0.         0.         0.
 0.         0.

In [40]:
model2 = DictionaryLearning(n_components=10, alpha=1, transform_algorithm='threshold', verbose=True)

In [41]:
results2 = model2.fit_transform(data)

[dict_learning] .++++++++.++++.++++.+++.++.+.+.+.+......................................................................


In [42]:
for row in results2:
    print(row)

[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0. -0. -0.  0.  0.  0. -0. -0. -0.  0.]
[-0.         -0.         -0.          0.00113422  0.          0.
 -0.       

In [43]:
results.shape

(500, 10)